### ISSUE TITLE
make failing 

### ISSUE THREAD

**Issue by rishavsharan** [amber-crystal/amber-cmd#54] opened 2017-07-12 14:48 UTC
Hi
I am installing amber on a new lubuntu vm. I ran `git clone https://github.com/Amber-Crystal/amber_cmd.git` followed by `shards install`

When i run make, i get an exception;

````
rick@forge:~/DevSpace/ambercr/amber_cmd$ make
Building amber in /home/rick/DevSpace/ambercr/amber_cmd
fork: Cannot allocate memory
0x5a9495: ??? at ??
0x1163325: ??? at ??
0x154f0cc: ??? at ??
0x148c9ec: ??? at ??
0x11c58f3: ??? at ??
0x10b2f9a: ??? at ??
0xf87524: ??? at ??
0xf84e79: ??? at ??
0xf8449c: ??? at ??
0xd52549: ??? at ??
0xf80b0c: ??? at ??
0xf7ba92: ??? at ??
0xd535c1: ??? at ??
0x1ce4655: ??? at ??
0x1cdb31f: ??? at ??
0x61d646: ??? at ??
0xf7e518: ??? at ??
0xd535c1: ??? at ??
0xd52604: ??? at ??
0x1ce4655: ??? at ??
0x1cdb31f: ??? at ??
0x61d646: ??? at ??
0xf7e518: ??? at ??
0xd535c1: ??? at ??
0xd52604: ??? at ??
0x1627c81: ??? at ??
0xd535f0: ??? at ??
0x169ffc2: ??? at ??
0x196287d: ??? at ??
0xd53c25: ??? at ??
0x1ce4655: ??? at ??
0x1cdb31f: ??? at ??
0x61d646: ??? at ??
0xf7e518: ??? at ??
0xd535c1: ??? at ??
0xf7d343: ??? at ??
0xd535c1: ??? at ??
0xf7d343: ??? at ??
0xd535c1: ??? at ??
0xd52604: ??? at ??
0xd52604: ??? at ??
0x1ce4655: ??? at ??
0x1cdb31f: ??? at ??
0x61d646: ??? at ??
0xf7e518: ??? at ??
0xd535c1: ??? at ??
0xd52604: ??? at ??
0x169f572: ??? at ??
0xd513a3: ??? at ??
0x169f572: ??? at ??
0xd513a3: ??? at ??
0x19d1140: ??? at ??
0xd53dd6: ??? at ??
0x1ce4655: ??? at ??
0x1cdb31f: ??? at ??
0x61d646: ??? at ??
0xf7e518: ??? at ??
0xd535c1: ??? at ??
0xd52604: ??? at ??
0x1ce4655: ??? at ??
0x1cdb31f: ??? at ??
0x61d646: ??? at ??
0xf7e518: ??? at ??
0xd535c1: ??? at ??
0x1ce4655: ??? at ??
0x1cdb31f: ??? at ??
0x61d646: ??? at ??
0xf7e518: ??? at ??
0xd535c1: ??? at ??
0x1627bcf: ??? at ??
0xd535f0: ??? at ??
0xd52604: ??? at ??
0x17b5f87: ??? at ??
0xd5409a: ??? at ??
0x1624449: ??? at ??
0x162b26f: ??? at ??
0xd51319: ??? at ??
0x17b5f87: ??? at ??
0xd5409a: ??? at ??
0x1ce4655: ??? at ??
0x1cdb31f: ??? at ??
0x61d646: ??? at ??
0xf7e518: ??? at ??
0xd535c1: ??? at ??
0x1624449: ??? at ??
0x162b26f: ??? at ??
0xd51319: ??? at ??
0x169f572: ??? at ??
0xd513a3: ??? at ??
0x1ce4655: ??? at ??
0x1cdb31f: ??? at ??
0x61d646: ??? at ??
0xf7e518: ??? at ??
0xd535c1: ??? at ??
0xd52604: ??? at ??
0x1ce4655: ??? at ??
0x1cdb31f: ??? at ??
0x61d646: ??? at ??
0xf7e518: ??? at ??
0xd535c1: ??? at ??
0x1ce4655: ??? at ??
0x1cdb31f: ??? at ??
0x61d646: ??? at ??
0xf7e518: ??? at ??
0xd535c1: ??? at ??
0x169f572: ??? at ??
0xd513a3: ??? at ??
0x1ce4655: ??? at ??
0x1cdb31f: ??? at ??
0x61d646: ??? at ??
0xf7e518: ??? at ??
0xd535c1: ??? at ??
0x1627bcf: ??? at ??
0xd535f0: ??? at ??
0xd52604: ??? at ??
0x17b5f87: ??? at ??
0xd5409a: ??? at ??
0x1624449: ??? at ??
0x162b26f: ??? at ??
0xd51319: ??? at ??
0x17b5f87: ??? at ??
0xd5409a: ??? at ??
0x1ce4655: ??? at ??
0x1cdb31f: ??? at ??
0x61d646: ??? at ??
0xf7e518: ??? at ??
0xd535c1: ??? at ??
0x1624449: ??? at ??
0x162b26f: ??? at ??
0xd51319: ??? at ??
0x169f572: ??? at ??
0xd513a3: ??? at ??
0x1ce4655: ??? at ??
0x1cdb31f: ??? at ??
0x61d646: ??? at ??
0xf7e518: ??? at ??
0xd535c1: ??? at ??
0xd52604: ??? at ??
0x1ce4655: ??? at ??
0x1cdb31f: ??? at ??
0x61d646: ??? at ??
0xf7e518: ??? at ??
0xd535c1: ??? at ??
0x1ce4655: ??? at ??
0x1cdb31f: ??? at ??
0x61d646: ??? at ??
0xf7e518: ??? at ??
0xd535c1: ??? at ??
0x1ce4655: ??? at ??
0x1cdb31f: ??? at ??
0x61d646: ??? at ??
0xf7e518: ??? at ??
0xd535c1: ??? at ??
0x1ce4655: ??? at ??
0x1cdb31f: ??? at ??
0x61d646: ??? at ??
0xf7e518: ??? at ??
0xd535c1: ??? at ??
0xd52604: ??? at ??
0x11f411f: ??? at ??
0x1d1be53: ??? at ??
0x60b551: ??? at ??
0x5d76d1: main at ??
0x7f38e99fc3f1: __libc_start_main at ??
0x5a4190: ??? at ??
0x0: ??? at ??

Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
Makefile:6: recipe for target 'build' failed
make: *** [build] Error 1
````

**Comment by elorest** [comment] 2017-07-12 15:35
Not a bug. You need more memory to compile. The easiest thing to do would
be to make a swap file of 2gbs.

sudo fallocate -l 2G /swapfile
sudo chown root:root /swapfile
sudo chmod 0600 /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile
sudo bash -c "echo '/swapfile       none    swap    sw      0       0
' >> /etc/fstab"

**Comment by rishavs** [comment] 2017-07-12 15:44
thanks. Changed memory allocation in vm to 2gb. now make is working fine.

I am getting a different exception now;

````
rick@forge:~/DevSpace/ambercr/amber_cmd$ make
Building amber in /home/rick/DevSpace/ambercr/amber_cmd
/usr/bin/ld: cannot find -lsqlite3
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc "${@}" -o '/home/rick/DevSpace/ambercr/amber_cmd/bin/amber'  -rdynamic  -lsqlite3 `command -v pkg-config > /dev/null && pkg-config --libs libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --libs libcrypto || printf %s '-lcrypto'` -lyaml -lreadline -lpcre -lm -lgc -lpthread /opt/crystal/src/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/usr/local/lib`
Makefile:6: recipe for target 'build' failed
make: *** [build] Error 1
````

**Comment by rishavs** [comment] 2017-07-12 15:47
As a followup;
can we update the installation instructions to include `sudo apt-get install libsqlite3-dev` as adependency installation.

**Comment by elorest** [comment] 2017-07-12 15:58
Could you submit a pr in gitbook for that? It note we need it for Ubuntu
but not OSX or other os's that have it installed by default.

**Comment by rishavs** [comment] 2017-07-12 18:43
How do i submit a PR in gitbook? sorry, i have never done it before.
Is there a git repository that i can goto and make the PR?

**Comment by elorest** [comment] 2017-07-13 23:55
@eliasjpr Could you weigh in on this. How does collaboration work on gitbook?

**Comment by elorest** [comment] 2017-07-14 17:36
Not sure that we should document this. Maybe we should have a list of deps that may or may not be already installed.

**Comment by jasdeepsingh** [comment] 2017-08-13 02:14
I think it should definitely be documented, I came searching through to this page out of my own failing `make`.

**Comment by jasdeepsingh** [comment] 2017-08-13 02:22
`sudo apt-get install libreadline-dev libsqlite3-dev libssl-dev` did the trick for me. If someone can point me where to send a PR - I can do the needful. New to gitbook as well.

**Comment by elorest** [comment] 2017-08-13 02:37
Send a PR for the readme on amber-cmd. For gitbook send a PR on this file.
https://github.com/amber-crystal/online-docs/blob/master/getting-started/Installation/README.md

Thanks a lot. I thought this had already been documented.

**Comment by drujensen** [comment] 2017-08-25 17:25
resolved in documentation

**Closed by drujensen** 2017-08-25 17:25 UTC
